### PR TITLE
fix: fix panic when multiple modifier keys and no main key

### PR DESCRIPTION
**Pull request by IAmJSD**

### CODE REVIEW

**Comment by amrbashir** [comment]
thank you

**Comment by cjpais** [comment]
Hi, I'm wondering if this should be a supported configuration @amrbashir 

Certainly the application should not panic when multiple modifier keys are set and no main key. However, it seems very reasonable for modifiers to be set without a main key. 

One primary application of this might be for a speech-to-text application where a user may want to hold down a modifier without any specific trigger key, and while they are holding down that button for audio recording to be happening, so it can be transcribed when the key is released.

Is this expected to be a supported configuration for this plugin? But if it's not, that's totally fine. It's just I would much prefer to use a supported plugin to do this as opposed to developing my own.

**Comment by amrbashir** [comment]
@cjpais it is not supported atm, but I am not opposed to adding it, unfortunately I may not have the time to in the near future, so contributions are always welcome or at the very least please open an issue.

**Comment by cjpais** [comment]
sounds good, I will try to make the contribution. I am not super familiar with tauri yet or the development process for a plugin, but will see what I can do. i will definitely want to try and replicate the original panic if I can as well, and make sure that case is nicely covered.

**Comment by cjpais** [comment]
So looking into this a little bit, it seems like it would necessitate a breaking change. 

Is this acceptable? @amrbashir 

The `HotKey` struct changing to have an option on `key`. And I guess really, it may make sense to change `mods` similarly. It would change the behavior from strictly 'global hotkey' to something more like detecting keypresses/combos of keypresses more generally

```
pub struct HotKey {
    /// The hotkey modifiers.
    pub mods: Modifiers,
    /// The hotkey key, if any.
    pub key: Option<Code>,
    /// The hotkey id.
    pub id: u32,
}
```

**Comment by amrbashir** [comment]
@cjpais let's open a PR and discuss there instead but you shouldn't need to break this struct, as single modifier hotkey should be treated as single key hotkey for example if we want hold-to-speak using `Ctrl` key, the Hotkey would have an empty `Modifiers` and the main key would be `Code::ControlLeft`

**Comment by cjpais** [comment]
Digging deeper, the key events are registered with platform specific calls it looks like (on MacOS `RegisterEventHotKey`), and these as far as I can tell do not support the configuration I am thinking about. Changing this behavior requires extra system permissions. I think it's best I make my own little library for this purpose. Thanks for the help, sorry for discussing too much here. I was hesitant to open a PR too early

**Pull request merged**
