### PR TITLE
feat: support registering media play/pause/stop/next/prev keys

### LINKED ISSUE #70: Media Keys
How can i listen for media keys like Play/Pause / Next etc.
Is this even possible and if not will this be implemented in the future?

### PR DESCRIPTION
**Pull request by amrbashir**
closes #70

### CODE REVIEW

**Comment by amrbashir** [comment]
@pewsheen could you research the macOS part? here is a few things I found: 
- https://stackoverflow.com/questions/114541/how-do-i-access-listen-for-the-multimedia-keys-play-pause-in-mac-os-x
- https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/chrome/browser/extensions/global_shortcut_listener_mac.mm

**Comment by pewsheen** [comment]
I pushed a WIP commit to another branch: https://github.com/tauri-apps/global-hotkey/commit/0f51409d8292080b9d328a7c2ead90cdd464b89f

There are some limitations on macOS:
- It requires adding a MachPort source into CFRunLoop (to listening OS events), this will trigger OS to request `Accessibility` permission
- It can only detect which media key is pressed. If you press `Cmd+MediaPlay`, we only know the `MediaPlay` button is pressed.
- Need to store EventTap and EventTapSource somewhere (Global?) to release it when we want to stop watching the media key
- We need to find a way to check the media key is registered and its hotkey ID inside the callback closure (maybe Global variable again?) so that we can emit the event to the hotkey event channel. Or we can just hardcode the ID and emit it every time, letting the user decide whether to handle it or not.

**Comment by amrbashir** [comment]
> There are some limitations on macOS:
> 
> * It requires adding a MachPort source into CFRunLoop (to listening OS events), this will trigger OS to request `Accessibility` permission

Does this need changes in plist file or it automatically requests it at runtime?

> * It can only detect which media key is pressed. If you press `Cmd+MediaPlay`, we only know the `MediaPlay` button is pressed.

Can't we check the NSEvent for modifiers?

> * Need to store EventTap and EventTapSource somewhere (Global?) to release it when we want to stop watching the media key

can we have multiple EventTap? if so, then store it on `GlobalHotkeyManager` and release it on drop

> * We need to find a way to check the media key is registered and its hotkey ID inside the callback closure (maybe Global variable again?) so that we can emit the event to the hotkey event channel. Or we can just hardcode the ID and emit it every time, letting the user decide whether to handle it or not.

`CGEventTapCreate` allows passing a pointer to a data, so you can create an `Arc<Mutex>` stored on `GlobalHotKeyManager`, that tracks if any media key is registered, then we clone it and convert it to a raw pointer and send it to the callback, that way you can check if it was registered

**Comment by pewsheen** [comment]
> Does this need changes in plist file or it automatically requests it at runtime?

It'll pop up automatically. Currently, it will only ask when registering media keys

I'm storing the event tap and media hotkey information in the `GlobalHotKeyManager` now. It will require the `register` and `unregister` to use `&mut self`

**Pull request merged**
