### PR TITLE
Better error messages on Windows for registration errors returned by OS

### PR DESCRIPTION
**Pull request by Exidex**
Better error messages on Windows for registration errors returned by OS. Instead of suppressing all other non-AlreadyRegistered errors, forward the error as OsError.

### CODE REVIEW

**Review by amrbashir — APPROVED** [review]

**Comment by amrbashir** [comment]
thank you

**Review by amrbashir — CHANGES_REQUESTED** [review]
looks like you need to run `cargo fmt`

**Comment by Exidex** [comment]
@amrbashir done

**Comment by amrbashir** [comment]
Thank you

**Pull request merged**
